<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Twig;

use MU\BoardModule\Twig\Base\AbstractTwigExtension;
use Symfony\Component\HttpKernel\Controller\ControllerReference;
use ServiceUtil;

/**
 * Twig extension implementation class.
 */
class TwigExtension extends AbstractTwigExtension
{
	/**
	 * Returns a list of custom Twig functions.
	 *
	 * @return \Twig_SimpleFunction[]
	 */
	public function getFunctions()
	{
        $functions = parent::getFunctions();
        $functions[] = new \Twig_SimpleFunction('muboardmodule_showEditForm', [$this, 'showEditForm'], ['is_safe' => ['html']]);
        
        return $functions;
	}
	
    public function showEditForm()
    {
    	$request = \ServiceUtil::get('request_stack')->getMasterRequest();
    	$request->attributes->set('_zkModule', 'MUBoardModule');
    
    	$fragmentHandler = \ServiceUtil::get('fragment.handler');
    
    	$ref = new ControllerReference('MUBoardModule:Posting:edit');
    
    	return $fragmentHandler->render($ref, 'inline', []);
    }
}
