<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Twig;

use MU\BoardModule\Twig\Base\AbstractTwigExtension;
use Symfony\Component\HttpKernel\Controller\ControllerReference;

use Zikula\Common\Translator\TranslatorInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use MU\BoardModule\Helper\ListEntriesHelper;
use MU\BoardModule\Helper\EntityDisplayHelper;
use MU\BoardModule\Helper\WorkflowHelper;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpKernel\Fragment\FragmentHandler;
use MU\BoardModule\Entity\Factory\EntityFactory;

/**
 * Twig extension implementation class.
 */
class TwigExtension extends AbstractTwigExtension
{
	/**
	 * @var Request
	 */
	protected $request;
	
	/**
	 * @var EntityFactory
	 */
	protected $entityFactory;
	
	/**
	 * @var FragmentHandler
	 */
	protected $fragmentHandler;
	
	/**
	 * TwigExtension constructor.
	 *
	 * @param TranslatorInterface $translator     Translator service instance
	 * @param VariableApiInterface   $variableApi    VariableApi service instance
	 * @param EntityDisplayHelper $entityDisplayHelper EntityDisplayHelper service instance
	 * @param WorkflowHelper      $workflowHelper WorkflowHelper service instance
	 * @param ListEntriesHelper   $listHelper     ListEntriesHelper service instance
	 * @param RequestStack           $requestStack     RequestStack service instance
	 * @param FragmentHandler    $fragmentHandler FragmentHandler service instance
	 * @param EntityFactory      $entityFactory   EntityFactory service instance
	 */
	public function __construct(
			TranslatorInterface $translator,
			VariableApiInterface $variableApi,
			EntityDisplayHelper $entityDisplayHelper,
			WorkflowHelper $workflowHelper,
			ListEntriesHelper $listHelper,
			RequestStack $requestStack,
			FragmentHandler $fragmentHandler,
			EntityFactory $entityFactory)
	{
		$this->setTranslator($translator);
		$this->variableApi = $variableApi;
		$this->entityDisplayHelper = $entityDisplayHelper;
		$this->workflowHelper = $workflowHelper;
		$this->listHelper = $listHelper;
		$this->request = $requestStack->getCurrentRequest();
		$this->fragmentHandler = $fragmentHandler;
		$this->entityFactory = $entityFactory;
	}
	
	/**
	 * Returns a list of custom Twig functions.
	 *
	 * @return \Twig_SimpleFunction[]
	 */
	public function getFunctions()
	{
        $functions = parent::getFunctions();
        $functions[] = new \Twig_SimpleFunction('muboardmodule_showEditForm', [$this, 'showEditForm'], ['is_safe' => ['html']]);
        $functions[] = new \Twig_SimpleFunction('muboardmodule_getForumId', [$this, 'getForumId'], ['is_safe' => ['html']]);
        $functions[] = new \Twig_SimpleFunction('muboardmodule_getPostingId', [$this, 'getPostingId'], ['is_safe' => ['html']]);
                
        return $functions;
	}
	
    public function showEditForm()
    {
    	$this->request->attributes->set('_zkModule', 'MUBoardModule');
    
    	$ref = new ControllerReference('MUBoardModule:Posting:edit',array() , array('forumid' => 1));
    
    	return $this->fragmentHandler->render($ref, 'inline', []);
    }
    
    public function getForumId()
    {
    	$postingId = $this->request->get('id', 0);
    	if ($postingId > 0) {
    	$postingRepository = $this->entityFactory->getRepository('posting');
    	$entity = $postingRepository->selectById($postingId);
    	return $entity['forum']['id'];   	
    	} else {
    		return '';
    	}
    }
    
    public function getPostingId()
    {
    	$postingId = $this->request->get('id');
    	if ($postingId > 0) {
    	return $postingId;
    	} else {
    		return '';
    	}
    }
}
