<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Jun 18 14:46:37 CEST 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MUBoard_user_edit() function.
 * It aims on the posting object type.
 */
class MUBoard_Form_Handler_User_Posting_Edit extends MUBoard_Form_Handler_User_Posting_Base_Edit
{
    /**
     * Initialize form handler.
     *
     * This method takes care of all necessary initialisation of our data and form states.
     *
     * @return boolean False in case of initialization errors, otherwise true.
     */
    public function initialize(Zikula_Form_View $view)
    {
    	parent::initialize($view);
    	
    	$forum = $this->request->query->filter('forum', 0, FILTER_SANITIZE_NUMBER_INT);  
    	  	
    	// set mode to create
    	$this->mode = 'create';
    	
    	// get modvars
    	$uploadImages = ModUtil::getVar('MUBoard', 'uploadImages');
    	$uploadFiles = ModUtil::getVar('MUBoard', 'uploadFiles');
    	$numberImages = ModUtil::getVar('MUBoard', 'numberImages');
    	$numberFiles = ModUtil::getVar('MUBoard', 'numberFiles');
    	
    	// we assign to template
    	$this->view->assign('uploadImages', $uploadImages)
    	           ->assign('uploadFiles', $uploadFiles)
    	           ->assign('numberImages', $numberImages)
    	           ->assign('numberFiles', $numberFiles)
    	           ->assign('mode', $this->mode)
    	           ->assign('forum', $forum);

        // everything okay, no initialization errors occured
    	return true;
    
    }    
}
