<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\ContentType\Base;

use Zikula\Common\Content\AbstractContentType;
use MU\BoardModule\ContentType\Form\Type\ItemListType as FormType;
use MU\BoardModule\Entity\Factory\EntityFactory;
use MU\BoardModule\Helper\ControllerHelper;
use MU\BoardModule\Helper\ModelHelper;

/**
 * Generic item list content type base class.
 */
abstract class AbstractItemListType extends AbstractContentType
{
    /**
     * @var ControllerHelper
     */
    protected $controllerHelper;
    
    /**
     * @var ModelHelper
     */
    protected $modelHelper;
    
    /**
     * @var EntityFactory
     */
    protected $entityFactory;
    
    /**
     * @inheritDoc
     */
    public function getIcon()
    {
        return 'th-list';
    }
    
    /**
     * @inheritDoc
     */
    public function getTitle()
    {
        return $this->translator->__('Board list', 'muboardmodule');
    }
    
    /**
     * @inheritDoc
     */
    public function getDescription()
    {
        return $this->translator->__('Display a list of board objects.', 'muboardmodule');
    }
    
    /**
     * @inheritDoc
     */
    public function getDefaultData()
    {
        return [
            'objectType' => 'category',
            'sorting' => 'default',
            'amount' => 1,
            'template' => 'itemlist_display.html.twig',
            'customTemplate' => null,
            'filter' => ''
        ];
    }
    
    /**
     * @inheritDoc
     */
    public function getData()
    {
        $data = parent::getData();
    
        $contextArgs = ['name' => 'list'];
        if (!isset($data['objectType']) || !in_array($data['objectType'], $this->controllerHelper->getObjectTypes('contentType', $contextArgs))) {
            $data['objectType'] = $this->controllerHelper->getDefaultObjectType('contentType', $contextArgs);
        }
    
        if (!isset($data['template'])) {
            $data['template'] = 'itemlist_' . $data['objectType'] . '_display.html.twig';
        }
        $this->data = $data;
    
        return $data;
    }
    
    /**
     * @inheritDoc
     */
    public function displayView()
    {
        $objectType = $this->data['objectType'];
        $repository = $this->entityFactory->getRepository($objectType);
    
        // create query
        $orderBy = $this->modelHelper->resolveSortParameter($this->data['objectType'], $this->data['sorting']);
        $qb = $repository->getListQueryBuilder($this->data['filter'], $orderBy);
    
        // get objects from database
        $currentPage = 1;
        $resultsPerPage = isset($this->data['amount']) ? $this->data['amount'] : 1;
        $query = $repository->getSelectWherePaginatedQuery($qb, $currentPage, $resultsPerPage);
        try {
            list($entities, $objectCount) = $repository->retrieveCollectionResult($query, true);
        } catch (\Exception $exception) {
            $entities = [];
            $objectCount = 0;
        }
    
        $data = $this->data;
        $data['items'] = $entities;
    
        $data = $this->controllerHelper->addTemplateParameters($objectType, $data, 'contentType', []);
        $this->data = $data;
    
        return parent::displayView();
    }
    
    /**
     * @inheritDoc
     */
    public function getViewTemplatePath($suffix = '')
    {
        $templateFile = $this->data['template'];
        if ('custom' == $templateFile && null !== $this->data['customTemplate'] && '' != $this->data['customTemplate']) {
            $templateFile = $this->data['customTemplate'];
        }
    
        $templateForObjectType = str_replace('itemlist_', 'itemlist_' . $this->data['objectType'] . '_', $templateFile);
    
        $templateOptions = [
            'ContentType/' . $templateForObjectType,
            'ContentType/' . $templateFile,
            'ContentType/itemlist_display.html.twig'
        ];
    
        $template = '';
        foreach ($templateOptions as $templatePath) {
            if ($this->twigLoader->exists('@MUBoardModule/' . $templatePath)) {
                $template = '@MUBoardModule/' . $templatePath;
                break;
            }
        }
    
        return $template;
    }
    
    /**
     * @inheritDoc
     */
    public function getEditFormClass()
    {
        return FormType::class;
    }
    
    /**
     * @inheritDoc
     */
    public function getEditFormOptions($context)
    {
        $options = parent::getEditFormOptions($context);
        $data = $this->getData();
        $options['object_type'] = $data['objectType'];
    
        return $options;
    }
    
    /**
     * @param ControllerHelper $controllerHelper
     */
    public function setControllerHelper(ControllerHelper $controllerHelper)
    {
        $this->controllerHelper = $controllerHelper;
    }
    
    /**
     * @param ModelHelper $modelHelper
     */
    public function setModelHelper(ModelHelper $modelHelper)
    {
        $this->modelHelper = $modelHelper;
    }
    
    /**
     * @param EntityFactory $entityFactory
     */
    public function setEntityFactory(EntityFactory $entityFactory)
    {
        $this->entityFactory = $entityFactory;
    }
}
