<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Sep 25 14:18:39 CEST 2012.
 */

/**
 * Generic item list content plugin implementation class
 */
class MUBoard_ContentType_ItemList extends MUBoard_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function MUBoard_Api_ContentTypes_itemlist($args)
{
    return new MUBoard_Api_ContentTypes_itemListPlugin();
}
