<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\BoardModule\Entity\UserEntity;

/**
 * Event base class for filtering user processing.
 */
class AbstractFilterUserEvent extends Event
{
    /**
     * @var UserEntity Reference to treated entity instance.
     */
    protected $user;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterUserEvent constructor.
     *
     * @param UserEntity $user Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(UserEntity $user, array $entityChangeSet = [])
    {
        $this->user = $user;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return UserEntity
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
