<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jun 15 09:09:36 CEST 2012.
 */

/**
 * This is the Admin api helper class.
 */
class MUBoard_Api_Admin extends MUBoard_Api_Base_Admin
{
    /**
     * get available Admin panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'main'),
                    'text' => $this->__('Frontend'),
                    'title' => $this->__('Switch to user area.'),
                    'class' => 'z-icon-es-home');
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'category')),
                    'text' => $this->__('Categories'),
                    'title' => $this->__('Category list'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'forum')),
                    'text' => $this->__('Forums'),
                    'title' => $this->__('Forum list'));
        }
        /*if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
         $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'posting')),
                 'text' => $this->__('Postings'),
                 'title' => $this->__('Posting list'));
        }*/
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url'   => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'user')),
                    'text'  => $this->__('Users'),
                    'title' => $this->__('User list'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url'   => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'rank')),
                    'text'  => $this->__('Ranks'),
                    'title' => $this->__('Rank list'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url'   => ModUtil::url($this->name, 'admin', 'import'),
                    'text'  => $this->__('Import'),
                    'title' => $this->__('Import of dizkus'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'config'),
                    'text' => $this->__('Configuration'),
                    'title' => $this->__('Manage settings for this application'));
        }
        return $links;
    }

    /**
     * import of dizkus datas
     */
    public function importDizkus($args)
    {
        $host = $args['host'];
        $dbname = $args['dbname'];
        $user = $args['user'];
        $password = $args['password'];
        $dizkustable = $args['dizkustable'];

        $connection = Doctrine_Manager::getInstance()->getConnection('default');
        
        if (!$connection) {
            $url = ModUtil::url($this->name, 'admin', 'import');
            LogUtil::registerError(__('Sorry. No connection to the database. Something went wrong!'));
            return System::redirect($url);
        }
         
        if ($dizkustable == 1 || $dizkustable == 2) {
            // we get all categories
            $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_categories`');
            $categories = $result->fetchAll(Doctrine::FETCH_ASSOC);

            $sqlContact = new mysqli($host, $user, $password, $dbname);
            
            if (mysqli_connect_errno()) {
                $url = ModUtil::url('MUBoard', 'admin', 'import');
                LogUtil::registerError(__('Sorry. No connection to the database. It seems your entered datas are wrong!'));
                return ModUtil::url('MUBoard', 'admin', 'import');
            }

            foreach ($categories as $category) {
                $title = $sqlContact->real_escape_string($category['cat_title']);
                $values = "('" . $category['cat_id'] . "', '" . $title . "', '', '" . $category['cat_order'] . "')";

                $sql = 'INSERT INTO muboard_category (id, title, description, pos) VALUES ' . $values;

                $stmt = $connection->prepare($sql);
                try {
                    $stmt->execute();
                } catch (Exception $e) {
                    LogUtil::registerError($e);
                }
            }
            $sqlContact->close();

        }

        if ($dizkustable == 1 || $dizkustable == 2) {
            // we get all forums
            $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_forums`');
            $forums = $result->fetchAll(Doctrine::FETCH_ASSOC);

            $sqlContact2 = new mysqli($host, $user, $password, $dbname);
            
            if (mysqli_connect_errno()) {
                $url = ModUtil::url($this->name, 'admin', 'import');
                LogUtil::registerError(__('Sorry. No connection to the database. It seems your entered datas are wrong!'));
                return System::redirect($url);
            }

            foreach ($forums as $forum) {
                $title = $sqlContact2->real_escape_string($forum['forum_name']);
                $description = $sqlContact2->real_escape_string($forum['forum_desc']);
                $values = "('" . $forum['forum_id'] . "', '" . $forum['cat_id'] . "', '" . $title . "', '" . $description . "', '" . $forum['forum_order'] . "')";

                $sql = 'INSERT INTO muboard_forum (id, category_id, title, description, pos) VALUES ' . $values;

                $stmt = $connection->prepare($sql);
                try {
                    $stmt->execute();
                } catch (Exception $e) {
                    LogUtil::registerError($e);
                }
            }
            
            // we get all subscriptions
            $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_subscription`');
            $subscriptions = $result->fetchAll(Doctrine::FETCH_ASSOC);
            
            foreach ($subscriptions as $subscription) {

                $values2 = "('" . $subscription['forum_id'] . "', '" . $subscription['user_id'] . "')";
            
                $sql2 = 'INSERT INTO muboard_abo (forumid, userid) VALUES ' . $values2;
            
                $stmt2 = $connection->prepare($sql2);
                try {
                    $stmt2->execute();
                } catch (Exception $e) {
                    LogUtil::registerError($e);
                }
            }
            
            $sqlContact2->close();
        }

        if ($dizkustable == 1 || $dizkustable == 3) {

            // we get all topics
            $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_topics`');
            $topics = $result->fetchAll(Doctrine::FETCH_ASSOC);

            $sqlContact3 = new mysqli($host, $user, $password, $dbname);
            
            if (mysqli_connect_errno()) {
                $url = ModUtil::url($this->name, 'admin', 'import');
                LogUtil::registerError(__('Sorry. No connection to the database. It seems your entered datas are wrong!'));
                return System::redirect($url);
            }

            foreach ($topics as $topic) {
                // we get all posts of this topic
                $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_posts` WHERE `topic_id` = ' . $topic['topic_id']);
                $posts = $result->fetchAll(Doctrine::FETCH_ASSOC);
                if (isset($posts)) {
                    $firstId = $posts[0]['post_id'];
                    $text = $posts[0]['post_text'];
                }
                $text = $sqlContact3->real_escape_string($text);
                $title = $sqlContact3->real_escape_string($topic['topic_title']);
                $values = "('" . $firstId . "', NULL, '" . $topic['forum_id'] . "', '" . $title . "', '" . $text . "', '" . $topic['topic_views'] . "', '" . "1" . "', '" . $topic['topic_poster'] . "', '" . $topic['topic_time'] . "', 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}')";

                $sql = 'INSERT INTO muboard_posting (id, parent_id, forum_id, title, text, invocations, state, createdUserId, createdDate, firstImageMeta, secondImageMeta, thirdImageMeta, firstFileMeta, secondFileMeta, thirdFileMeta) VALUES ' . $values;

                $stmt = $connection->prepare($sql);
                try {
                    $stmt->execute();
                    foreach ($posts as $post) {
                        if ($post['post_id'] != $firstId) {
                            $text2 = $sqlContact3->real_escape_string($post['post_text']);
                            $values2 = "('" . $post['post_id'] . "', '" . $firstId . "', '" . $post['forum_id'] . "', '" . $text2 . "', '" . $post['poster_id'] . "', '" . $post['post_time'] . "', 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}', 'a:0:{}')";

                            $sql2 = 'INSERT INTO muboard_posting (id, parent_id, forum_id, text, createdUserId, createdDate, firstImageMeta, secondImageMeta, thirdImageMeta, firstFileMeta, secondFileMeta, thirdFileMeta) VALUES ' . $values2;
                            $stmt2 = $connection->prepare($sql2);
                            try {
                                $stmt2->execute();

                            } catch (Exception $f) {
                                LogUtil::registerError($f);
                            }
                        }
                    }

                } catch (Exception $e) {
                    LogUtil::registerError($e);
                }
            }
            $sqlContact3->close();
        }

        if ($dizkustable == 1 || $dizkustable == 4) {
            // we get all users
            $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_users`');
            $users = $result->fetchAll(Doctrine::FETCH_ASSOC);

            $sqlContact4 = new mysqli($host, $user, $password, $dbname);
            
            if (mysqli_connect_errno()) {
                $url = ModUtil::url($this->name, 'admin', 'import');
                LogUtil::registerError(__('Sorry. No connection to the database. It seems your entered datas are wrong!'));
                return System::redirect($url);
            }

            foreach ($users as $user) {
                $values = "('" . $user['user_rank'] . "', '" . $user['user_id'] . "', '" . $user['user_posts'] . "', '" . $user['user_lastvisit'] . "')";

                $sql = 'INSERT INTO muboard_user (rank_id, userid, numberPostings, lastVisit) VALUES ' . $values;

                $stmt = $connection->prepare($sql);
                try {
                    $stmt->execute();
                } catch (Exception $e) {
                    LogUtil::registerError($e);
                }
            }

            // we get all users
            $result = DBUtil::executeSQL('SELECT * FROM `z_dizkus_ranks`');
            $ranks = $result->fetchAll(Doctrine::FETCH_ASSOC);

            foreach ($ranks as $rank) {
                $numberOfIcons = $this->numberOfIcons($rank['rank_image']);
                $name = $sqlContact4->real_escape_string($rank['rank_title']);
                $values = "('" . $rank['rank_id'] . "', '" . $name . "', '" . $rank['rank_min'] . "', '" . $rank['rank_max'] . "', '" . $numberOfIcons . "', 'a:0:{}', '" . $rank['rank_special'] . "')";

                $sql = 'INSERT INTO muboard_rank (id, name, minPostings, maxPostings, numberOfIcons, uploadImageMeta, special) VALUES ' . $values;

                $stmt = $connection->prepare($sql);
                try {
                    $stmt->execute();
                } catch (Exception $e) {
                    LogUtil::registerError($e);
                }
            }
            $sqlContact4->close();
        }

    }
    /**
     * This function return the number of icons
     * depending on gif file in dizkus
     * @param string $icon
     * @return int number
     */

    private function numberOfIcons($icon)
    {
        switch ($icon) {
            case 'zerostar.gif':
                return 0;
            case 'onestar.gif':
                return 1;
            case 'twostars.gif':
                return 2;
            case 'threestars.gif':
                return 3;
            case 'fourstars.gif':
                return 4;
            case 'fivestars.gif':
                return 5;
        }

    }

    /**
     * this function change the forum for the children of a posting
     * $args
     */
    public function movetoforum($args)
    {
        $work = $this->request->query->filter('work', 'none', FILTER_SANITIZE_STRING);

        $args['postingid'] = $this->getId();
        $forum = $args['forum'];
        $children = $args['children'];
        if ($work == 'movetoforum') {
             
            $serviceManager = ServiceUtil::getManager();
            $entityManager = $serviceManager->getService('doctrine.entitymanager');
             
            $postingrepository = MUBoard_Util_Model::getPostingRepository();
            foreach ($children as $child) {
                $posting = $postingrepository->selectById($child['id']);
                $posting->setForum($forum);
                $entityManager->flush();
            }
        }
    }
}
