<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Oct 14 15:42:51 CEST 2012.
 */

/**
 * Selection api implementation class
 */
class MUBoard_Api_Selection extends MUBoard_Api_Base_Selection
{
    /**
     * @param int args[uid]     userid
     */
    public function userOnline($args)
    {
        $uid = $args['uid'];
        $tables = DBUtil::getTables();
        $columns = $tables['session_info_column'];
        $where = "$columns[uid] = '" . DataUtil::formatForStore($uid) . "'";
        return DBUtil::selectObject('session_info', $where);
    }
}
