<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Oct 14 15:42:51 CEST 2012.
 */

/**
 * This is the Ajax api helper class.
 */
class MUBoard_Api_Ajax extends MUBoard_Api_Base_Ajax
{
	public function preview() {
		
		include_once 'lib/viewplugins/function.useravatar.php';
		
		$dom = ZLanguage::getModuleDomain('MUBoard');
		
		$text = $this->request->getGet()->filter('text', '', FILTER_SANITIZE_STRING);
		$text = nl2br($text);
		$text = ModUtil::apiFunc('BBSmile', 'user', 'transform', array('text' => $text));
		
		$uid = UserUtil::getVar('uid');
		if ($uid > 1) {
		$uname = UserUtil::getVar('uname', $uid);
		} else {
		    $uname = __('Guest', $dom);
		}
		
		$userRank = MUBoard_Util_View::getUserRank($uid);

		$date = DateUtil::getDatetime(null,'datetimelong');
		
		if ($uid > 1) {
		$params['uid'] = $uid;
		$params['size'] = 60;
		$avatar = smarty_function_useravatar($params);
		}
		else {
		    $avatar = '';
		}
		
		$out = "";
		$out .= "<div class='muboard-user-posting muboard-preview'>";
		$out .= "<div class='muboard-user-posting-user'>";
		$out .= "<div class='muboard-user-posting-avatar'>";
		$out .= $avatar . "<br />";
		$out .= $uname;		
		$out .= "</div>";
		$out .= "<div class='muboard-user-posting-datas'>";
		$out .= $userRank;		
		$out .= "</div>";		
		$out .= "</div>";	
		$out .= "<div class='muboard-user-posting-content'>";
		$out .= "<div class='muboard-user-posting-created'>";
		$out .= $date;
		$out .= "</div>";
		$out .= "<div class='muboard-user-posting-content-text'>";
		$out .= $text;			
		$out .= "</div>";	
		$out .= "</div>";
		$out .= "</div>";

		return $out;
	}
}
