<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Sep 25 14:18:39 CEST 2012.
 */

/**
 * This is the Search api helper class.
 */
class MUBoard_Api_Search extends MUBoard_Api_Base_Search
{
    /**
* Search plugin info
*/
    public function info()
    {
        return array('title' => 'MUBoard',
            'functions' => array('muboard' => 'search'));
    }
    
    /**
* Search form component
*/
    public function options($args)
    {
        if (SecurityUtil::checkPermission('MUBoard::', '::', ACCESS_READ)) {
            // Create output object - this object will store all of our output so that
            // we can return it easily when required
            $render = Zikula_View::getInstance('MUBoard');
            $render->assign('active', !isset($args['active']) || isset($args['active']['MUBoard']));
            return $render->fetch('search/options.tpl');
        }

        return '';
    }
}
