<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Form\Handler\Rank;

use MU\BoardModule\Form\Handler\Rank\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the mUBoardModule_rank_edit() function.
 * It aims on the rank object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
