<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Jun 18 14:46:37 CEST 2012.
 */

/**
 * Utility implementation class for controller helper methods.
 */
class MUBoard_Util_Controller extends MUBoard_Util_Base_Controller
{

	/**
	 * Helper method to handle the mailing for abos of postings forums
	 */
	
	public static function aboMailing()
	{
		
	}
}
