<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jun 15 09:09:36 CEST 2012.
 */

/**
 * Utility implementation class for model helper methods.
 */
class MUBoard_Util_Model extends MUBoard_Util_Base_Model
{
	
	/**
	 * This function counts the call of a posting
	 * @param id   id of the ticket to close
	 */

	public static function closeTicket($id) {

		// build ticket repository
		$repository = MUBoard_Util_Model::getPostingRepository();

		$entity = $repository->selectById($id);

		$serviceManager = ServiceUtil::getManager();
		$entityManager = $serviceManager->getService('doctrine.entitymanager');

		$invocation = $entity->getInvocations();
		$entity->setInvocations($invocation + 1);

		$entityManager->flush();

		return true;

	}
	
	/**
	 *
	 This method is for getting a repository for category
	 *
	 */

	public static function getCategoryRepository() {

		$serviceManager = ServiceUtil::getManager();
		$entityManager = $serviceManager->getService('doctrine.entitymanager');
		$repository = $entityManager->getRepository('MUBoard_Entity_Category');

		return $repository;
	}
	
	/**
	 *
	 This method is for getting a repository for forum
	 *
	 */

	public static function getForumRepository() {

		$serviceManager = ServiceUtil::getManager();
		$entityManager = $serviceManager->getService('doctrine.entitymanager');
		$repository = $entityManager->getRepository('MUBoard_Entity_Forum');

		return $repository;
	}
	
	/**
	 *
	 This method is for getting a repository for posting
	 *
	 */

	public static function getPostingRepository() {

		$serviceManager = ServiceUtil::getManager();
		$entityManager = $serviceManager->getService('doctrine.entitymanager');
		$repository = $entityManager->getRepository('MUBoard_Entity_Posting');

		return $repository;
	}
}
