<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Form\Type;

use MU\BoardModule\Form\Type\Base\AbstractUserType;

/**
 * User editing form type implementation class.
 */
class UserType extends AbstractUserType
{
    // feel free to extend the user editing form type class here
}
