services:
    mu_board_module.app_settings:
        class: MU\BoardModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
