<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Sep 25 14:18:39 CEST 2012.
 */

/**
 * Installer implementation class
 */
class MUBoard_Installer extends MUBoard_Base_Installer
{
        /**
     * Install the MUBoard application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {    
        $this->setVar('sortingCategories', array('descending'));
        
        parent::install();
    }
}
