<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Oct 14 15:42:51 CEST 2012.
 */

/**
 * Installer base class
 */
class MUBoard_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the MUBoard application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('posting', 'firstImage');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('posting', 'secondImage');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('posting', 'thirdImage');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('posting', 'firstFile');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('posting', 'secondFile');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('posting', 'thirdFile');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUBoard_Util_Controller::getFileBaseFolder('rank', 'uploadImage');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }

        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while creating the tables for the %s module.', array($this->getName())));
        }

        // set up all our vars with initial values
        $this->setVar('uploadImages', false);
        $this->setVar('allowedSizeOfImages', 0);
        $this->setVar('numberImages', array('1'));
        $this->setVar('uploadFiles', false);
        $this->setVar('allowedSizeOfFiles', 0);
        $this->setVar('numberFiles', array('1'));
        $this->setVar('editPostings', false);
        $this->setVar('editTime', 6);
        $this->setVar('latestPostings', 1);
        $this->setVar('sortingPostings', array('descending'));
        $this->setVar('iconSet', array('1'));
        $this->setVar('template', array('normal'));
        $this->setVar('pagesize', 10);
        $this->setVar('standardIcon', 'images/icons/extrasmall/favorites.png');
        $this->setVar('specialIcon', 'images/icons/extrasmall/package_favorite.png');

        // create the default data for MUBoard
        $this->createDefaultData();

        // register persistent event handlers
        $this->registerPersistentEventHandlers();

        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());

        // initialisation successful
        return true;
    }

    /**
     * Upgrade the MUBoard application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldversion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldversion)
    {
        /*
         // Upgrade dependent on old version number
         switch ($oldversion) {
         case 1.0.0:
         // do something
         // ...
         // update the database schema
         try {
         DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
         } catch (Exception $e) {
         if (System::isDevelopmentMode()) {
         LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
         }
         return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s module.', array($this->getName())));
         }
         }
         */

        // update successful
        return true;
    }

    /**
     * Uninstall MUBoard.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s module.', array($this->getName())));
        }

        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s module.', array($this->getName())));
        }

        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers('MUBoard');

        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());

        // remove all module vars
        $this->delVars();

        // deletion successful
        return true;
    }

    /**
     * Build array with all entity classes for MUBoard.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'MUBoard_Entity_Category';
        $classNames[] = 'MUBoard_Entity_Forum';
        $classNames[] = 'MUBoard_Entity_Posting';
        $classNames[] = 'MUBoard_Entity_Abo';
        $classNames[] = 'MUBoard_Entity_User';
        $classNames[] = 'MUBoard_Entity_Rank';

        return $classNames;
    }
    /**
     * Create the default data for MUBoard.
     *
     * @return void
     */
    protected function createDefaultData()
    {
        // Ensure that tables are cleared
        $this->entityManager->transactional(function ($entityManager)
        {
            $entityManager->getRepository('MUBoard_Entity_Category')->truncateTable();
            $entityManager->getRepository('MUBoard_Entity_Forum')->truncateTable();
            $entityManager->getRepository('MUBoard_Entity_Posting')->truncateTable();
            $entityManager->getRepository('MUBoard_Entity_Abo')->truncateTable();
            $entityManager->getRepository('MUBoard_Entity_User')->truncateTable();
            $entityManager->getRepository('MUBoard_Entity_Rank')->truncateTable();
        }
        );

        // Insertion successful
        return true;
    }

    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core
        EventUtil::registerPersistentModuleHandler('MUBoard', 'api.method_not_found', array('MUBoard_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'core.preinit', array('MUBoard_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'core.init', array('MUBoard_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'core.postinit', array('MUBoard_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'controller.method_not_found', array('MUBoard_Listener_Core', 'controllerMethodNotFound'));

        // installer
        EventUtil::registerPersistentModuleHandler('MUBoard', 'installer.module.installed', array('MUBoard_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'installer.module.upgraded', array('MUBoard_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'installer.module.uninstalled', array('MUBoard_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'installer.subscriberarea.uninstalled', array('MUBoard_Listener_Installer', 'subscriberAreaUninstalled'));

        // modules
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module_dispatch.postloadgeneric', array('MUBoard_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module_dispatch.preexecute', array('MUBoard_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module_dispatch.postexecute', array('MUBoard_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module_dispatch.custom_classname', array('MUBoard_Listener_ModuleDispatch', 'customClassname'));

        // mailer
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.mailer.api.sendmessage', array('MUBoard_Listener_Mailer', 'sendMessage'));

        // page
        EventUtil::registerPersistentModuleHandler('MUBoard', 'pageutil.addvar_filter', array('MUBoard_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'system.outputfilter', array('MUBoard_Listener_Page', 'systemOutputfilter'));

        // errors
        EventUtil::registerPersistentModuleHandler('MUBoard', 'setup.errorreporting', array('MUBoard_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'systemerror', array('MUBoard_Listener_Errors', 'systemError'));

        // theme
        EventUtil::registerPersistentModuleHandler('MUBoard', 'theme.preinit', array('MUBoard_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'theme.init', array('MUBoard_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'theme.load_config', array('MUBoard_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'theme.prefetch', array('MUBoard_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'theme.postfetch', array('MUBoard_Listener_Theme', 'postFetch'));

        // view
        EventUtil::registerPersistentModuleHandler('MUBoard', 'view.init', array('MUBoard_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'view.postfetch', array('MUBoard_Listener_View', 'postFetch'));

        // user login
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.login.started', array('MUBoard_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.login.veto', array('MUBoard_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.login.succeeded', array('MUBoard_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.login.failed', array('MUBoard_Listener_UserLogin', 'failed'));

        // user logout
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.logout.succeeded', array('MUBoard_Listener_UserLogout', 'succeeded'));

        // user
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.gettheme', array('MUBoard_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.account.create', array('MUBoard_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.account.update', array('MUBoard_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.account.delete', array('MUBoard_Listener_User', 'delete'));

        // registration
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.registration.started', array('MUBoard_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.registration.succeeded', array('MUBoard_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.ui.registration.failed', array('MUBoard_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.registration.create', array('MUBoard_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.registration.update', array('MUBoard_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'user.registration.delete', array('MUBoard_Listener_UserRegistration', 'delete'));

        // users module
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.users.config.updated', array('MUBoard_Listener_Users', 'configUpdated'));

        // group
        EventUtil::registerPersistentModuleHandler('MUBoard', 'group.create', array('MUBoard_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'group.update', array('MUBoard_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'group.delete', array('MUBoard_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'group.adduser', array('MUBoard_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'group.removeuser', array('MUBoard_Listener_Group', 'removeUser'));

        // special purposes and 3rd party api support
        EventUtil::registerPersistentModuleHandler('MUBoard', 'get.pending_content', array('MUBoard_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('MUBoard', 'module.content.gettypes', array('MUBoard_Listener_ThirdParty', 'contentGetTypes'));
    }
}
