<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Sep 25 14:18:39 CEST 2012.
 */

/**
 * The muboardSelectorObjectTypes plugin provides items for a dropdown selector.
 *
 * Available parameters:
 *   - assign:   If set, the results are assigned to the corresponding variable instead of printed out.
 *
 * @param  array            $params  All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view    Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_muboardSelectorObjectTypes($params, $view)
{
    $result = array();

    $result[] = array('text' => $view->__('Categories'), 'value' => 'category');
    $result[] = array('text' => $view->__('Forums'), 'value' => 'forum');
    $result[] = array('text' => $view->__('Postings'), 'value' => 'posting');
    $result[] = array('text' => $view->__('Abos'), 'value' => 'abo');
    $result[] = array('text' => $view->__('Users'), 'value' => 'user');
    $result[] = array('text' => $view->__('Ranks'), 'value' => 'rank');

    if (array_key_exists('assign', $params)) {
        $view->assign($params['assign'], $result);
        return;
    }
    return $result;
}
