<?php
use Gedmo\Mapping\Annotation\Language;

/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Oct 14 15:42:51 CEST 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MUBoard_admin_edit() function.
 * It aims on the posting object type.
 */
class MUBoard_Form_Handler_Admin_Posting_Edit extends MUBoard_Form_Handler_Admin_Posting_Base_Edit
{
        /**
     * Initialize form handler.
     *
     * This method takes care of all necessary initialisation of our data and form states.
     *
     * @return boolean False in case of initialization errors, otherwise true.
     */
    public function initialize(Zikula_Form_View $view) {
    	
    	$work = $this->request->query->filter('work', 'none', FILTER_SANITIZE_STRING);
    	
    	$this->view->assign('work', $work);
    	
    	return parent::initialize($view);
    }
    
    /**
     * Command event handler.
     *
     * This event handler is called when a command is issued by the user.
     */
    public function handleCommand(Zikula_Form_View $view, &$args)
    {
        parent::HandleCommand($view, $args);
        
        $dom = ZLanguage::getModuleDomain($this->name);
        // we handle the redirect to the frontend after moving an issue
        // to another forum
        $work = $this->request->query->filter('work', 'none', FILTER_SANITIZE_STRING);
        $id = $this->request->query->filter('id', 0, FILTER_SANITIZE_NUMBER_INT);
        if ($id > 0) {
            $url = ModUtil::url($this->name, 'user', 'display', array('ot' => 'posting', 'id' => $id));
            return LogUtil::registerStatus(__('Done! Moving of issue successful.', $dom), $url);
        } else {
            $url = ModUtil::url($this->name, 'user');
            LogUtil::registerError('Sorry! Moving the issue failed', $dom);
        }
        return System::redirect($url);
        
    }
}