<?php
/**
 * MUBoard.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUBoard
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Oct 14 15:42:51 CEST 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MUBoard_admin_edit() function.
 * It aims on the posting object type.
 */
class MUBoard_Form_Handler_Admin_Posting_Edit extends MUBoard_Form_Handler_Admin_Posting_Base_Edit
{
        /**
     * Initialize form handler.
     *
     * This method takes care of all necessary initialisation of our data and form states.
     *
     * @return boolean False in case of initialization errors, otherwise true.
     */
    public function initialize(Zikula_Form_View $view) {
    	
    	$work = $this->request->query->filter('work', 'none', FILTER_SANITIZE_STRING);
    	
    	$this->view->assign('work', $work);
    	
    	return parent::initialize($view);
    }
}
