<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Zikula\Core\Doctrine\EntityAccess;
use MU\BoardModule\Traits\StandardFieldsTrait;
use MU\BoardModule\Validator\Constraints as BoardAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for posting entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractPostingEntity extends EntityAccess
{
    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'posting';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @BoardAssert\ListEntry(entityName="posting", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var integer $parent_id
     */
    protected $parent_id = 0;
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="255")
     * @var string $title
     */
    protected $title = '';
    
    /**
     * @ORM\Column(type="text", length=20000)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="20000")
     * @var text $text
     */
    protected $text = '';
    
    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(type="integer")
     * @Assert\NotNull()
     * @Assert\LessThan(value=100000000000)
     * @var integer $invocations
     */
    protected $invocations = 0;
    
    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull()
     * @Assert\Type(type="bool")
     * @var boolean $state
     */
    protected $state = false;
    
    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull()
     * @Assert\Type(type="bool")
     * @var boolean $solved
     */
    protected $solved = false;
    
    /**
     * First image meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $firstImageMeta
     */
    protected $firstImageMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "200k",
     *    mimeTypes = {"image/*"}
     * )
     * @Assert\Image(
     * )
     * @var string $firstImage
     */
    protected $firstImage = null;
    
    /**
     * Full first image path as url.
     *
     * @Assert\Type(type="string")
     * @var string $firstImageUrl
     */
    protected $firstImageUrl = '';
    
    /**
     * Second image meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $secondImageMeta
     */
    protected $secondImageMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "200k",
     *    mimeTypes = {"image/*"}
     * )
     * @Assert\Image(
     * )
     * @var string $secondImage
     */
    protected $secondImage = null;
    
    /**
     * Full second image path as url.
     *
     * @Assert\Type(type="string")
     * @var string $secondImageUrl
     */
    protected $secondImageUrl = '';
    
    /**
     * Third image meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $thirdImageMeta
     */
    protected $thirdImageMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "200k",
     *    mimeTypes = {"image/*"}
     * )
     * @Assert\Image(
     * )
     * @var string $thirdImage
     */
    protected $thirdImage = null;
    
    /**
     * Full third image path as url.
     *
     * @Assert\Type(type="string")
     * @var string $thirdImageUrl
     */
    protected $thirdImageUrl = '';
    
    /**
     * First file meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $firstFileMeta
     */
    protected $firstFileMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "2M",
     *    mimeTypes = {"application/*"}
     * )
     * @var string $firstFile
     */
    protected $firstFile = null;
    
    /**
     * Full first file path as url.
     *
     * @Assert\Type(type="string")
     * @var string $firstFileUrl
     */
    protected $firstFileUrl = '';
    
    /**
     * Second file meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $secondFileMeta
     */
    protected $secondFileMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "2M",
     *    mimeTypes = {"application/*"}
     * )
     * @var string $secondFile
     */
    protected $secondFile = null;
    
    /**
     * Full second file path as url.
     *
     * @Assert\Type(type="string")
     * @var string $secondFileUrl
     */
    protected $secondFileUrl = '';
    
    /**
     * Third file meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $thirdFileMeta
     */
    protected $thirdFileMeta = [];
    
    /**
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    maxSize = "2M",
     *    mimeTypes = {"application/*"}
     * )
     * @var string $thirdFile
     */
    protected $thirdFile = null;
    
    /**
     * Full third file path as url.
     *
     * @Assert\Type(type="string")
     * @var string $thirdFileUrl
     */
    protected $thirdFileUrl = '';
    
    
    /**
     * Bidirectional - Many children [postings] are linked by one parent [posting] (OWNING SIDE).
     *
     * @ORM\ManyToOne(targetEntity="MU\BoardModule\Entity\PostingEntity", inversedBy="children")
     * @ORM\JoinTable(name="mu_board_posting",
     *      joinColumns={@ORM\JoinColumn(name="id", referencedColumnName="id" )},
     *      inverseJoinColumns={@ORM\JoinColumn(name="parent_id", referencedColumnName="id" )}
     * )
     * @Assert\Type(type="MU\BoardModule\Entity\PostingEntity")
     * @var \MU\BoardModule\Entity\PostingEntity $parent
     */
    protected $parent;
    
    /**
     * Bidirectional - Many posting [postings] are linked by one forum [forum] (OWNING SIDE).
     *
     * @ORM\ManyToOne(targetEntity="MU\BoardModule\Entity\ForumEntity", inversedBy="posting")
     * @ORM\JoinTable(name="mu_board_forum")
     * @Assert\Type(type="MU\BoardModule\Entity\ForumEntity")
     * @var \MU\BoardModule\Entity\ForumEntity $forum
     */
    protected $forum;
    
    /**
     * Bidirectional - One parent [posting] has many children [postings] (INVERSE SIDE).
     *
     * @ORM\OneToMany(targetEntity="MU\BoardModule\Entity\PostingEntity", mappedBy="parent", cascade={"remove"})
     * @ORM\JoinTable(name="mu_board_parentchildren",
     *      joinColumns={@ORM\JoinColumn(name="parent_id", referencedColumnName="id" )},
     *      inverseJoinColumns={@ORM\JoinColumn(name="id", referencedColumnName="id" )}
     * )
     * @var \MU\BoardModule\Entity\PostingEntity[] $children
     */
    protected $children = null;
    
    
    /**
     * PostingEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
        $this->children = new ArrayCollection();
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        if ($this->_objectType != $_objectType) {
            $this->_objectType = $_objectType;
        }
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        if (intval($this->id) !== intval($id)) {
            $this->id = intval($id);
        }
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = isset($workflowState) ? $workflowState : '';
        }
    }
    
    /**
     * Returns the parent_id.
     *
     * @return integer
     */
    public function getParent_id()
    {
        return $this->parent_id;
    }
    
    /**
     * Sets the parent_id.
     *
     * @param integer $parent_id
     *
     * @return void
     */
    public function setParent_id($parent_id)
    {
        if (intval($this->parent_id) !== intval($parent_id)) {
            $this->parent_id = intval($parent_id);
        }
    }
    
    /**
     * Returns the title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * Sets the title.
     *
     * @param string $title
     *
     * @return void
     */
    public function setTitle($title)
    {
        if ($this->title !== $title) {
            $this->title = isset($title) ? $title : '';
        }
    }
    
    /**
     * Returns the text.
     *
     * @return text
     */
    public function getText()
    {
        return $this->text;
    }
    
    /**
     * Sets the text.
     *
     * @param text $text
     *
     * @return void
     */
    public function setText($text)
    {
        if ($this->text !== $text) {
            $this->text = isset($text) ? $text : '';
        }
    }
    
    /**
     * Returns the invocations.
     *
     * @return integer
     */
    public function getInvocations()
    {
        return $this->invocations;
    }
    
    /**
     * Sets the invocations.
     *
     * @param integer $invocations
     *
     * @return void
     */
    public function setInvocations($invocations)
    {
        if (intval($this->invocations) !== intval($invocations)) {
            $this->invocations = intval($invocations);
        }
    }
    
    /**
     * Returns the state.
     *
     * @return boolean
     */
    public function getState()
    {
        return $this->state;
    }
    
    /**
     * Sets the state.
     *
     * @param boolean $state
     *
     * @return void
     */
    public function setState($state)
    {
        if (boolval($this->state) !== boolval($state)) {
            $this->state = boolval($state);
        }
    }
    
    /**
     * Returns the solved.
     *
     * @return boolean
     */
    public function getSolved()
    {
        return $this->solved;
    }
    
    /**
     * Sets the solved.
     *
     * @param boolean $solved
     *
     * @return void
     */
    public function setSolved($solved)
    {
        if (boolval($this->solved) !== boolval($solved)) {
            $this->solved = boolval($solved);
        }
    }
    
    /**
     * Returns the first image.
     *
     * @return string
     */
    public function getFirstImage()
    {
        return $this->firstImage;
    }
    
    /**
     * Sets the first image.
     *
     * @param string $firstImage
     *
     * @return void
     */
    public function setFirstImage($firstImage)
    {
        if ($this->firstImage !== $firstImage) {
            $this->firstImage = $firstImage;
        }
    }
    
    /**
     * Returns the first image url.
     *
     * @return string
     */
    public function getFirstImageUrl()
    {
        return $this->firstImageUrl;
    }
    
    /**
     * Sets the first image url.
     *
     * @param string $firstImageUrl
     *
     * @return void
     */
    public function setFirstImageUrl($firstImageUrl)
    {
        if ($this->firstImageUrl !== $firstImageUrl) {
            $this->firstImageUrl = $firstImageUrl;
        }
    }
    
    /**
     * Returns the first image meta.
     *
     * @return array
     */
    public function getFirstImageMeta()
    {
        return $this->firstImageMeta;
    }
    
    /**
     * Sets the first image meta.
     *
     * @param array $firstImageMeta
     *
     * @return void
     */
    public function setFirstImageMeta($firstImageMeta = [])
    {
        if ($this->firstImageMeta !== $firstImageMeta) {
            $this->firstImageMeta = $firstImageMeta;
        }
    }
    
    /**
     * Returns the second image.
     *
     * @return string
     */
    public function getSecondImage()
    {
        return $this->secondImage;
    }
    
    /**
     * Sets the second image.
     *
     * @param string $secondImage
     *
     * @return void
     */
    public function setSecondImage($secondImage)
    {
        if ($this->secondImage !== $secondImage) {
            $this->secondImage = $secondImage;
        }
    }
    
    /**
     * Returns the second image url.
     *
     * @return string
     */
    public function getSecondImageUrl()
    {
        return $this->secondImageUrl;
    }
    
    /**
     * Sets the second image url.
     *
     * @param string $secondImageUrl
     *
     * @return void
     */
    public function setSecondImageUrl($secondImageUrl)
    {
        if ($this->secondImageUrl !== $secondImageUrl) {
            $this->secondImageUrl = $secondImageUrl;
        }
    }
    
    /**
     * Returns the second image meta.
     *
     * @return array
     */
    public function getSecondImageMeta()
    {
        return $this->secondImageMeta;
    }
    
    /**
     * Sets the second image meta.
     *
     * @param array $secondImageMeta
     *
     * @return void
     */
    public function setSecondImageMeta($secondImageMeta = [])
    {
        if ($this->secondImageMeta !== $secondImageMeta) {
            $this->secondImageMeta = $secondImageMeta;
        }
    }
    
    /**
     * Returns the third image.
     *
     * @return string
     */
    public function getThirdImage()
    {
        return $this->thirdImage;
    }
    
    /**
     * Sets the third image.
     *
     * @param string $thirdImage
     *
     * @return void
     */
    public function setThirdImage($thirdImage)
    {
        if ($this->thirdImage !== $thirdImage) {
            $this->thirdImage = $thirdImage;
        }
    }
    
    /**
     * Returns the third image url.
     *
     * @return string
     */
    public function getThirdImageUrl()
    {
        return $this->thirdImageUrl;
    }
    
    /**
     * Sets the third image url.
     *
     * @param string $thirdImageUrl
     *
     * @return void
     */
    public function setThirdImageUrl($thirdImageUrl)
    {
        if ($this->thirdImageUrl !== $thirdImageUrl) {
            $this->thirdImageUrl = $thirdImageUrl;
        }
    }
    
    /**
     * Returns the third image meta.
     *
     * @return array
     */
    public function getThirdImageMeta()
    {
        return $this->thirdImageMeta;
    }
    
    /**
     * Sets the third image meta.
     *
     * @param array $thirdImageMeta
     *
     * @return void
     */
    public function setThirdImageMeta($thirdImageMeta = [])
    {
        if ($this->thirdImageMeta !== $thirdImageMeta) {
            $this->thirdImageMeta = $thirdImageMeta;
        }
    }
    
    /**
     * Returns the first file.
     *
     * @return string
     */
    public function getFirstFile()
    {
        return $this->firstFile;
    }
    
    /**
     * Sets the first file.
     *
     * @param string $firstFile
     *
     * @return void
     */
    public function setFirstFile($firstFile)
    {
        if ($this->firstFile !== $firstFile) {
            $this->firstFile = $firstFile;
        }
    }
    
    /**
     * Returns the first file url.
     *
     * @return string
     */
    public function getFirstFileUrl()
    {
        return $this->firstFileUrl;
    }
    
    /**
     * Sets the first file url.
     *
     * @param string $firstFileUrl
     *
     * @return void
     */
    public function setFirstFileUrl($firstFileUrl)
    {
        if ($this->firstFileUrl !== $firstFileUrl) {
            $this->firstFileUrl = $firstFileUrl;
        }
    }
    
    /**
     * Returns the first file meta.
     *
     * @return array
     */
    public function getFirstFileMeta()
    {
        return $this->firstFileMeta;
    }
    
    /**
     * Sets the first file meta.
     *
     * @param array $firstFileMeta
     *
     * @return void
     */
    public function setFirstFileMeta($firstFileMeta = [])
    {
        if ($this->firstFileMeta !== $firstFileMeta) {
            $this->firstFileMeta = $firstFileMeta;
        }
    }
    
    /**
     * Returns the second file.
     *
     * @return string
     */
    public function getSecondFile()
    {
        return $this->secondFile;
    }
    
    /**
     * Sets the second file.
     *
     * @param string $secondFile
     *
     * @return void
     */
    public function setSecondFile($secondFile)
    {
        if ($this->secondFile !== $secondFile) {
            $this->secondFile = $secondFile;
        }
    }
    
    /**
     * Returns the second file url.
     *
     * @return string
     */
    public function getSecondFileUrl()
    {
        return $this->secondFileUrl;
    }
    
    /**
     * Sets the second file url.
     *
     * @param string $secondFileUrl
     *
     * @return void
     */
    public function setSecondFileUrl($secondFileUrl)
    {
        if ($this->secondFileUrl !== $secondFileUrl) {
            $this->secondFileUrl = $secondFileUrl;
        }
    }
    
    /**
     * Returns the second file meta.
     *
     * @return array
     */
    public function getSecondFileMeta()
    {
        return $this->secondFileMeta;
    }
    
    /**
     * Sets the second file meta.
     *
     * @param array $secondFileMeta
     *
     * @return void
     */
    public function setSecondFileMeta($secondFileMeta = [])
    {
        if ($this->secondFileMeta !== $secondFileMeta) {
            $this->secondFileMeta = $secondFileMeta;
        }
    }
    
    /**
     * Returns the third file.
     *
     * @return string
     */
    public function getThirdFile()
    {
        return $this->thirdFile;
    }
    
    /**
     * Sets the third file.
     *
     * @param string $thirdFile
     *
     * @return void
     */
    public function setThirdFile($thirdFile)
    {
        if ($this->thirdFile !== $thirdFile) {
            $this->thirdFile = $thirdFile;
        }
    }
    
    /**
     * Returns the third file url.
     *
     * @return string
     */
    public function getThirdFileUrl()
    {
        return $this->thirdFileUrl;
    }
    
    /**
     * Sets the third file url.
     *
     * @param string $thirdFileUrl
     *
     * @return void
     */
    public function setThirdFileUrl($thirdFileUrl)
    {
        if ($this->thirdFileUrl !== $thirdFileUrl) {
            $this->thirdFileUrl = $thirdFileUrl;
        }
    }
    
    /**
     * Returns the third file meta.
     *
     * @return array
     */
    public function getThirdFileMeta()
    {
        return $this->thirdFileMeta;
    }
    
    /**
     * Sets the third file meta.
     *
     * @param array $thirdFileMeta
     *
     * @return void
     */
    public function setThirdFileMeta($thirdFileMeta = [])
    {
        if ($this->thirdFileMeta !== $thirdFileMeta) {
            $this->thirdFileMeta = $thirdFileMeta;
        }
    }
    
    
    /**
     * Returns the parent.
     *
     * @return \MU\BoardModule\Entity\PostingEntity
     */
    public function getParent()
    {
        return $this->parent;
    }
    
    /**
     * Sets the parent.
     *
     * @param \MU\BoardModule\Entity\PostingEntity $parent
     *
     * @return void
     */
    public function setParent($parent = null)
    {
        $this->parent = $parent;
    }
    
    /**
     * Returns the forum.
     *
     * @return \MU\BoardModule\Entity\ForumEntity
     */
    public function getForum()
    {
        return $this->forum;
    }
    
    /**
     * Sets the forum.
     *
     * @param \MU\BoardModule\Entity\ForumEntity $forum
     *
     * @return void
     */
    public function setForum($forum = null)
    {
        $this->forum = $forum;
    }
    
    /**
     * Returns the children.
     *
     * @return \MU\BoardModule\Entity\PostingEntity[]
     */
    public function getChildren()
    {
        return $this->children;
    }
    
    /**
     * Sets the children.
     *
     * @param \MU\BoardModule\Entity\PostingEntity[] $children
     *
     * @return void
     */
    public function setChildren($children)
    {
        foreach ($this->children as $postingSingle) {
            $this->removeChildren($postingSingle);
        }
        foreach ($children as $postingSingle) {
            $this->addChildren($postingSingle);
        }
    }
    
    /**
     * Adds an instance of \MU\BoardModule\Entity\PostingEntity to the list of children.
     *
     * @param \MU\BoardModule\Entity\PostingEntity $posting The instance to be added to the collection
     *
     * @return void
     */
    public function addChildren(\MU\BoardModule\Entity\PostingEntity $posting)
    {
        $this->children->add($posting);
        $posting->setParent($this);
    }
    
    /**
     * Removes an instance of \MU\BoardModule\Entity\PostingEntity from the list of children.
     *
     * @param \MU\BoardModule\Entity\PostingEntity $posting The instance to be removed from the collection
     *
     * @return void
     */
    public function removeChildren(\MU\BoardModule\Entity\PostingEntity $posting)
    {
        $this->children->removeElement($posting);
        $posting->setParent(null);
    }
    
    
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array The resulting arguments list
     */
    public function createUrlArgs()
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     *
     * @return integer The identifier
     */
    public function getKey()
    {
        return $this->getId();
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'muboardmodule.ui_hooks.postings';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects The objects are added to this array. Default: []
     * 
     * @return array of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = []) 
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Posting ' . $this->getKey() . ': ' . $this->getTitle();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        // reset upload fields
        $this->setFirstImage(null);
        $this->setFirstImageMeta([]);
        $this->setFirstImageUrl('');
        $this->setSecondImage(null);
        $this->setSecondImageMeta([]);
        $this->setSecondImageUrl('');
        $this->setThirdImage(null);
        $this->setThirdImageMeta([]);
        $this->setThirdImageUrl('');
        $this->setFirstFile(null);
        $this->setFirstFileMeta([]);
        $this->setFirstFileUrl('');
        $this->setSecondFile(null);
        $this->setSecondFileMeta([]);
        $this->setSecondFileUrl('');
        $this->setThirdFile(null);
        $this->setThirdFileMeta([]);
        $this->setThirdFileUrl('');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    }
}
