<?php
/**
 * Board.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BoardModule\Form\Type\Finder;

use MU\BoardModule\Form\Type\Finder\Base\AbstractForumFinderType;

/**
 * Forum finder form type implementation class.
 */
class ForumFinderType extends AbstractForumFinderType
{
    // feel free to extend the base form type class here
}
